name: Build Mod
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write  # <--- нужно обязательно!


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set Android SDK tools
        run: echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup gradle
        run: |
          chmod +x gradlew

      - name: Build library
        run: |
          ./gradlew :lib:deploy

      - name: Upload library artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: MultiCrafterLib
          path: lib/build/tmp/deploy/MultiCrafterLib.zip
          if-no-files-found: warn
