name: Release
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set Android SDK tools
        run: echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build library
        run: |
          chmod +x gradlew
          ./gradlew :lib:deploy

      - name: Move building
        run: |
          mkdir out
          cp lib/build/tmp/deploy/MultiCrafterLib.zip out/

      - name: Upload building
        uses: actions/upload-artifact@v4
        with:
          name: MultiCrafter
          path: out/*

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: "v2.0.0"
        run: |
          gh release create "$VERSION" --title "MultiCrafter Lib v$VERSION" out/*